### ISSUE TITLE
"Dangerous Win32.Trojan.612" alert from Chrome and 360 Security

### ISSUE THREAD

**Issue by sunbyte** [OsandaMalith/Cryptculator#1]
Hello Osanda!

Love your work as a penetration tester. I learned a lot from you, Thanks!
I noticed that Google Chrome and 360 Security detect your Cryptculator.exe as "Dangerous Win32.Trojan.612".  

:/

**Comment by OsandaMalith** [comment]
Thank you sunbyte for the feedback! 

It's clearly a flase positive. Maybe it's because I've packed it using UPX. I've uploaded a .7z archive instead of the direct exe, since Chrome won't allow direct exe's to download from untrusted sources.
There's nothing malicious in the code :blush:

**Comment by sunbyte** [comment]
I can confirm it's false positive. 
I had the same issue with server software written in Java (.jar). 
Keep the good work mate. :P

**Comment by OsandaMalith** [comment]
Even Java? :rofl:  yeah nowadays AV products are so paranoid!

Thanks again sunbyte :)
